### PR TITLE
[Done] Profile routes

### PR DESCRIPTION
**Pull request by Saurav-Shrivastav**

### CODE REVIEW

**Comment by jsparmani** [comment]
😃 Yeah, it's back again without conflicts

**Comment by Saurav-Shrivastav** [comment]
And it's working!

**Comment by jsparmani** [comment]
I am not able to update hostel @Saurav-Shrivastav . Can u please check that once.

**Comment by jsparmani** [comment]
@Saurav-Shrivastav does this use the hostel name to update it?

**Comment by Saurav-Shrivastav** [comment]
> @Saurav-Shrivastav does this use the hostel name to update it? I haven't ran it but just to confirm we will be adding hostels by their pk

@jsparmani Yes I have used the hostel name in the current implementation. Will change it to work according to the pk then.

**Comment by jsparmani** [comment]
Nice 👍

**Pull request merged**
