### PR TITLE
[WIP] Fixes for login page

### PR DESCRIPTION
**Pull request by kush-daga**

### CODE REVIEW

**Comment by kush-daga** [comment]
@jsparmani You can merge now

**Comment by jsparmani** [comment]
Ok

**Comment by kush-daga** [comment]
Ok I'll fix it

**Comment by kush-daga** [comment]
@jsparmani Check now

**Comment by jsparmani** [comment]
> @jsparmani Check now

I think u forgot to push it

**Comment by kush-daga** [comment]
I did push

**Comment by kush-daga** [comment]
Fixed overflow is the commit

**Comment by jsparmani** [comment]
Oh, sorry

**Comment by kush-daga** [comment]
@jsparmani I also pushed fixes for styling of product page

**Pull request merged**
