### PR TITLE
[Done] Wishlist integrated

### PR DESCRIPTION
**Pull request by aniketbiswas21**

### CODE REVIEW

**Comment by jsparmani** [comment]
Okay, sorry I forgot to review this. Will do it today @aniketbiswas21

**Comment by jsparmani** [comment]
@aniketbiswas21 How does removing from wishlist work?

**Comment by jsparmani** [comment]
> @aniketbiswas21 How does removing from wishlist work? Adding works prefectly. Also we need something to show the status whether it is already wishlisted or not

**Comment by aniketbiswas21** [comment]
@jsparmani Yes, I have not made that functionality yet. Will do it.

**Comment by jsparmani** [comment]
@aniketbiswas21 any updates on the delete function?

**Comment by aniketbiswas21** [comment]
@jsparmani  Sorry, I forgot. Will do it after some time.

**Pull request merged**
