### PR TITLE
[WIP] Added searchbar transition

### PR DESCRIPTION
**Pull request by parthsujalshah**
Added the transition effect in the search bar. It just needs to be positioned at the center

### CODE REVIEW

**Comment by kush-daga** [comment]
Whats going on with this? Status?

**Comment by jsparmani** [comment]
> Whats going on with this? Status?

The homepage is ready, improvisations on the scroll transition going on

**Comment by jsparmani** [comment]
@kush-daga can u review the home page once

**Comment by kush-daga** [comment]
Okay ill check

**Comment by kush-daga** [comment]
Its fine for now, there are some style changes that needs to be done, but ill do that after this gets merged.

**Comment by jsparmani** [comment]
> The transition seems fine but we need to center the search bar on scroll and ThaparX has to disappear when scrolled. Also the Topbar needs to be fixed at one place. I wasn't able to do that.

@aniketbiswas21 can u give this a try in the updates that @parthsujalshah has made.

**Comment by aniketbiswas21** [comment]
Sure @jsparmani

**Comment by aniketbiswas21** [comment]
@jsparmani still working

**Comment by jsparmani** [comment]
@all-contributors please add @parthsujalshah for code

**Comment by jsparmani** [comment]
@all-contributors please add @aniketbiswas21 for code, design

**Comment by jsparmani** [comment]
@all-contributors please add @Saurav-Shrivastav for code

**Comment by jsparmani** [comment]
@all-contributors please add @kush-daga for code, design

**Comment by jsparmani** [comment]
@all-contributors please add @jakebolam for code, maintenance, tests, docs

**Comment by jsparmani** [comment]
@all-contributors please add @jsparmani  for code, maintenance, tests, docs

**Comment by jsparmani** [comment]
@all-contributors please add @shubhank-saxena for tests, docs

**Comment by jsparmani** [comment]
@all-contributors please add @shreyagupta30 for docs

**Comment by jsparmani** [comment]
@all-contributors please add @all-contributors for docs

**Pull request closed without merging**
