### PR TITLE
[WIP] Added Product Page

### PR DESCRIPTION
**Pull request by aniketbiswas21**

### CODE REVIEW

**Comment by jsparmani** [comment]
@kush-daga I was thinking of a soln, where the user can click on the carousel image / long press on a carousel image to view the full image, probably insta style or a popup. Review the current product page first, if you feel that's fine, we shall proceed with the image view option.

**Comment by kush-daga** [comment]
That is a good idea but what about in desktop then?

**Comment by jsparmani** [comment]
> That is a good idea but what about in desktop then?

I guess, for desktop that could work on clicking on carousel image

**Comment by kush-daga** [comment]
@jsparmani Merge kardo

**Pull request merged**
