### PR TITLE
Added some scroll effects

### PR DESCRIPTION
**Pull request by aniketbiswas21**

### CODE REVIEW

**Comment by kush-daga** [comment]
Is it complete now? The scroll animation.. I'll review it then

**Comment by jsparmani** [comment]
> Is it complete now? The scroll animation.. I'll review it then

Haan, dekhle ek baari

**Comment by aniketbiswas21** [comment]
@kush-daga Did you check this?

**Comment by kush-daga** [comment]
Sorry got busy with sthg
WIll check it out rn

**Comment by kush-daga** [comment]
@jsparmani Can you run the master branch?
Im getting some errors.. Login is getting rendered, but not other routes

**Comment by kush-daga** [comment]
Ok ignore got the product route running

**Comment by kush-daga** [comment]
@jsparmani @aniketbiswas21 Only product route working, no other, any issues?

**Comment by aniketbiswas21** [comment]
@kush-daga Home is not working? Profile and myprofile are private routes. And for the profile route you need a id as a parameter in the link

**Comment by aniketbiswas21** [comment]
Check the routes folder for reference

**Comment by kush-daga** [comment]
Yep I did, /home was having issues

**Comment by aniketbiswas21** [comment]
it's working perfectly fine in mine. Have you populated the db?

**Comment by kush-daga** [comment]
Hmm maybe that's the issue will do it

**Pull request merged**
