### PR TITLE
[WIP] added dockerfile and docker-compose

### PR DESCRIPTION
**Pull request by parthsujalshah**
Dockerfile.dev added
docker folder set up
.dockerignore added

### CODE REVIEW

**Comment by jsparmani** [comment]
- [ ]There is something wrong in the configuration, the server isn't running when i do `docker-compose up`  after building it.
- [ ] Also, I recommend setting up volumes for `node_modules` and the rest of the app separately, to optimize the speed and avoid getting our `node_modules` replacing the one in container.

**Comment by shubhank-saxena** [comment]
@parthsujalshah I am not able to understand the Dockerfile. What is it's purpose and what's it doing right now?
I am not very sure @jsparmani that this is the time when you should focus on dockerization. It's usually done when you are ready with your modules and the way you wanna run them!

**Comment by parthsujalshah** [comment]
@shubhank-saxena docker file is:
1. Pulling node image from docker hub
2. Making a folder and specifying it as a default folder for our project frontend. All the client side code will be here
3. It is copying package.json to work directory
4. Running command 'yarn' to install node_modules. (It is able to run because it pulled the image of node)
5. Copying the remaining folders in workdir
6. Now we have project setup with node_modules installed in the container we can run the app. So it does yarn start.
This Dockerfile.dev is only for development and there will be a separate Dockerfile for production.

When we setup Travis ci each pull requested will be tested first before merging. We need docker for that.

**Comment by shubhank-saxena** [comment]
> When we setup Travis ci each pull requested will be tested first before merging. We need docker for that.

Not sure how this works! Would suggest to keep single dev.dockerfile as production one won't be added here in the repo!

**Pull request closed without merging**
