### PR TITLE
Login page added

### PR DESCRIPTION
**Pull request by aniketbiswas21**

### CODE REVIEW

**Comment by jsparmani** [comment]
@aniketbiswas21 The vertical scroll is not there but now there's some extra whitespace on right end and bottom end.
image

Also, there are still some compilation warnings that can be removed.

**Comment by aniketbiswas21** [comment]
Working on it.

**Comment by aniketbiswas21** [comment]
I can't seem to fix the overflow issue, I have been trying since yesterday. Can you help me out?

**Comment by jsparmani** [comment]
> I can't seem to fix the overflow issue, I have been trying since yesterday. Can you help me out?

It's strange, yesterday I was able to see the vertical overflow, but today it's not there. Now there's some white space on right and bottom end. Are you able to see that using the developer tools when switching to different mobile screens?

**Comment by aniketbiswas21** [comment]
Yes, I see them.

**Comment by aniketbiswas21** [comment]
@kush-daga Please help me out with this

**Comment by kush-daga** [comment]
I'll do it. Don't worry about this

**Comment by jsparmani** [comment]
@aniketbiswas21 merged this PR, @kush-daga would solve issue #40 in a seperate PR.

**Pull request merged**
